apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventfund-dev
  namespace: argocd
  labels:
    environment: dev
    managed-by: root-app
spec:
  project: default
  
  source:
    repoURL: https://github.com/kieuphat159/Eventfund-platform.git
    targetRevision: dev
    path: k8s/overlays/dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: eventfund-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
