apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventfund-prod
  namespace: argocd
  labels:
    environment: prod
    managed-by: root-app
spec:
  project: default
  
  source:
    repoURL: https://github.com/kieuphat159/Eventfund-platform.git
    targetRevision: master
    path: k8s/overlays/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: eventfund-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
