apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eventfund-backend-secret
  namespace: eventfund-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: eventfund-backend-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /eventfund/dev/backend
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/eventfund/dev/backend/(.*)"
            target: "$1"
