name: Scan – SonarQube (Full Project)

on:
  workflow_dispatch:
  push:
    branches: [dev, main, ci/cd]

jobs:
  sonarqube-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan (full project)
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=truongtrongdat94_eventfund-platform
            -Dsonar.organization=truongtrongdat94
            -Dsonar.sources=backend/src,frontend/src
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
